[metadata]
name = libcng_dpapi
version = attr: libcng_dpapi._version.__version__
description = Python bindings for libcng-dpapi C library
long_description = file: README.md
long_description_content_type = text/markdown
license = GPLv2
author = Author
author_email = august@altlinux.org
maintainer = Author
maintainer_email = august@altlinux.org
keywords = dpapi, cryptography, windows, security, encryption
url = https://github.com/august-alt/libcng-dpapi
project_urls =
	Homepage = https://github.com/august-alt/libcng-dpapi
	Repository = https://github.com/august-alt/libcng-dpapi.git
	Bug Tracker = https://github.com/august-alt/libcng-dpapi/issues
classifiers =
	Development Status :: 3 - Alpha
	Intended Audience :: Developers
	Operating System :: OS Independent
	Programming Language :: Python :: 3
	Programming Language :: Python :: 3.8
	Programming Language :: Python :: 3.9
	Programming Language :: Python :: 3.10
	Programming Language :: Python :: 3.11
	Programming Language :: Python :: 3.12
	Topic :: Security :: Cryptography
	Topic :: Software Development :: Libraries :: Python Modules

[options]
python_requires = >=3.8
package_dir =
	= src
packages = find:
include_package_data = True

[options.packages.find]
where = src

[options.extras_require]
dev =
	black>=22.0
	flake8>=5.0
	mypy>=1.0
